### ISSUE TITLE
css

### ISSUE THREAD

**Issue by mshekera** [winnlab/AgushaHuge#7]
Push fucking .css files to repository. There are always problems with recompiling, why wouldn't you just make them exist already compiled?
![image](https://cloud.githubusercontent.com/assets/2587088/5189203/67681dc4-74e4-11e4-8b56-f4785441cab9.png)

**Comment by HydraOrc** [comment]
Это Рома захотел удалить их, я как раз за то, чтобы они были.
Поставь https://github.com/chriseppstein/sass-css-importer, тогда у тебя скомпилится.

**Comment by Rastopyr** [comment]
Воу воу. одно дело css файлы плагинов(которые так же ставятся через bower), другое дело вещи которые компилируются через scss автоматически.

**Comment by HydraOrc** [comment]
Мы как раз говорим про "вещи которые компилируются через scss автоматически"

**Comment by mshekera** [comment]
Какой смысл каждый раз при развертывании в новом месте 10 минут вспоминать/гуглить/узнавать про `--update` и/или `sass-css-importer`?
Ошибка на скрине, к слову, как раз в мейн.цсс

**Comment by Rastopyr** [comment]
Давно пора взять грунт/гюльп и не париться

**Comment by mshekera** [comment]
Давно пора убрать `css/` из `.gitignore` и не париться.

**Comment by mshekera** [comment]
wtf?

```
Warning: missing space before text for line 23 of jade file "/home/olmdar/Projects/AgushaHuge/lib/../public/views/user/helpers/menus/right_menu_mustache.jade"
Warning: missing space before text for line 24 of jade file "/home/olmdar/Projects/AgushaHuge/lib/../public/views/user/helpers/menus/right_menu_mustache.jade"
Warning: missing space before text for line 34 of jade file "/home/olmdar/Projects/AgushaHuge/lib/../public/views/user/helpers/menus/right_menu_mustache.jade
```

Мне нужно перекомпилировать все цссники просто потому, что кто-то "убрал пробел" (утрирую) в одном из них?
![image](https://cloud.githubusercontent.com/assets/2587088/5221311/21da6c20-767f-11e4-9668-89e1cb0f7c29.png)

К слову, после перекомпиляции и проблема внешнего вида, и missing space "ушли".

**Comment by Rastopyr** [comment]
jade ругается на мусташ скорее всего

<h3>Неверно:</h3>

```
{{#if statement}}
    .someClass= someContent
{{/if}}
```

<h3>Верно:</h3>

```
{{#if statement}}
.someClass= someContent
{{/if}}
```

**Comment by mshekera** [comment]
Судя по blame, Руслан что-то не поделил с [отступами](https://github.com/winnlab/agusha-frontend/blame/master/views/user/helpers/menus/right_menu_mustache.jade) (или наоборот, исправил то, что ты "не поделил", т.к. сейчас ошибки вроде нет), но с темой эта ошибка все же имеет мало общего.
