### ISSUE TITLE
Errors after send email

### ISSUE THREAD

**Issue by Rastopyr** [winnlab/AgushaHuge#9]
[Error: Data command failed - 550 5.4.5 Daily sending quota exceeded. j9sm3551776wjb.38 - gsmtp]
  data: '550 5.4.5 Daily sending quota exceeded. j9sm3551776wjb.38 - gsmtp',
  stage: 'data'

**Comment by HydraOrc** [comment]
Там на сервисе ограничения - около 30 писем в полчаса.
Я как раз вчера по Диминой просьбе начал отсылать 60 штук, видимо исчерпал.
Оно скорее всего уже прошло, если только там нету более 30 регистраций в полчаса.
